name: Domain
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Domain
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          debug: true
          script: |
            cd ~/projects/jiko-auth

            git pull origin main

            sudo cp auth.with-jiko.com /etc/nginx/sites-available/
            sudo ln -sf /etc/nginx/sites-available/auth.with-jiko.com /etc/nginx/sites-enabled/

            sudo nginx -t
            sudo systemctl reload nginx